<?php
/**
 * AXIS UPGRADERS - ADMIN PANEL
 * Edits public/site-content.json and uploads site images.
 */

session_start();

$content_file = __DIR__ . '/../site-content.json';
$auth_file    = __DIR__ . '/.auth.php';

// ──────────────────────────────────────────────────────────────
// Auth: setup → login → session
// ──────────────────────────────────────────────────────────────

function render_auth_page($title, $heading, $body_html, $error = '') {
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?php echo htmlspecialchars($title); ?></title>
        <style>
            body {
                font-family: 'Inter', system-ui, sans-serif;
                background: #0f1115;
                color: #e0e0e0;
                margin: 0;
                min-height: 100vh;
                display: grid;
                place-items: center;
                padding: 40px 20px;
                box-sizing: border-box;
            }
            .auth-card {
                background: #1a1d23;
                border: 1px solid #2d333b;
                border-radius: 8px;
                padding: 32px;
                width: 100%;
                max-width: 380px;
            }
            .auth-card h1 {
                color: #c8a25d;
                margin: 0 0 6px;
                font-size: 1.3rem;
                letter-spacing: 0.05em;
                text-transform: uppercase;
            }
            .auth-card h2 {
                margin: 0 0 24px;
                font-size: 1rem;
                font-weight: 500;
                color: #aaa;
            }
            .auth-card label {
                display: block;
                margin: 14px 0 6px;
                font-size: 0.8rem;
                color: #888;
            }
            .auth-card input[type="password"],
            .auth-card input[type="text"] {
                width: 100%;
                background: #000;
                border: 1px solid #2d333b;
                color: white;
                padding: 10px;
                border-radius: 4px;
                box-sizing: border-box;
                font-size: 0.95rem;
            }
            .auth-card button {
                width: 100%;
                margin-top: 22px;
                background: #c8a25d;
                color: black;
                border: none;
                padding: 12px;
                border-radius: 4px;
                cursor: pointer;
                font-weight: 700;
                font-size: 0.95rem;
                letter-spacing: 0.04em;
            }
            .auth-card button:hover { filter: brightness(1.1); }
            .auth-error {
                background: #3a1e1e;
                color: #f87171;
                padding: 10px 12px;
                border-radius: 4px;
                font-size: 0.85rem;
                margin-bottom: 14px;
            }
            .auth-hint {
                margin-top: 18px;
                font-size: 0.78rem;
                color: #666;
                line-height: 1.55;
            }
        </style>
    </head>
    <body>
        <div class="auth-card">
            <h1>AXIS ADMIN</h1>
            <h2><?php echo htmlspecialchars($heading); ?></h2>
            <?php if ($error): ?>
                <div class="auth-error"><?php echo htmlspecialchars($error); ?></div>
            <?php endif; ?>
            <?php echo $body_html; ?>
        </div>
    </body>
    </html>
    <?php
}

// Logout
if (isset($_GET['logout'])) {
    $_SESSION = [];
    session_destroy();
    header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
    exit;
}

// First-run setup: no auth file yet → user picks an initial password.
if (!file_exists($auth_file)) {
    $err = '';
    if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['setup_password'])) {
        $pw  = (string)($_POST['new_password'] ?? '');
        $pw2 = (string)($_POST['confirm_password'] ?? '');
        if (strlen($pw) < 6) {
            $err = 'Password must be at least 6 characters.';
        } else if ($pw !== $pw2) {
            $err = 'Passwords do not match.';
        } else {
            $hash = password_hash($pw, PASSWORD_DEFAULT);
            $contents = "<?php\n// Auto-generated by admin. Do not edit by hand.\nreturn ['hash' => " . var_export($hash, true) . "];\n";
            if (file_put_contents($auth_file, $contents) === false) {
                $err = 'Could not write ' . basename($auth_file) . '. Check folder permissions.';
            } else {
                @chmod($auth_file, 0600);
                $_SESSION['admin_auth'] = true;
                header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
                exit;
            }
        }
    }
    $body = '<form method="POST">
        <label>New Password (min 6 chars)</label>
        <input type="password" name="new_password" autofocus required>
        <label>Confirm Password</label>
        <input type="password" name="confirm_password" required>
        <button type="submit" name="setup_password" value="1">Set Password</button>
        <p class="auth-hint">No admin password is set yet. This page is the first-run setup — pick a strong password and save it somewhere safe. You can change it later from inside the admin.</p>
    </form>';
    render_auth_page('Set Admin Password — Axis', 'Set Initial Password', $body, $err);
    exit;
}

$auth_data   = include $auth_file;
$stored_hash = is_array($auth_data) ? ($auth_data['hash'] ?? '') : '';

// Login
if (empty($_SESSION['admin_auth'])) {
    $err = '';
    if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['admin_login'])) {
        $pw = (string)($_POST['password'] ?? '');
        if ($stored_hash && password_verify($pw, $stored_hash)) {
            session_regenerate_id(true);
            $_SESSION['admin_auth'] = true;
            header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
            exit;
        }
        $err = 'Incorrect password.';
        // Small delay to make brute-forcing more expensive
        usleep(400000);
    }
    $body = '<form method="POST">
        <label>Password</label>
        <input type="password" name="password" autofocus required>
        <button type="submit" name="admin_login" value="1">Log In</button>
    </form>';
    render_auth_page('Admin Login — Axis', 'Sign in to edit content', $body, $err);
    exit;
}

// Past here: user is authenticated.

// Change-password handling (form posts back to same page with change_password flag).
$password_change_msg   = '';
$password_change_error = false;
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['change_password'])) {
    $cur     = (string)($_POST['current_password'] ?? '');
    $new     = (string)($_POST['new_password'] ?? '');
    $confirm = (string)($_POST['confirm_password'] ?? '');
    if (!password_verify($cur, $stored_hash)) {
        $password_change_msg = 'Current password is incorrect.';
        $password_change_error = true;
    } else if (strlen($new) < 6) {
        $password_change_msg = 'New password must be at least 6 characters.';
        $password_change_error = true;
    } else if ($new !== $confirm) {
        $password_change_msg = 'New passwords do not match.';
        $password_change_error = true;
    } else {
        $hash = password_hash($new, PASSWORD_DEFAULT);
        $contents = "<?php\n// Auto-generated by admin. Do not edit by hand.\nreturn ['hash' => " . var_export($hash, true) . "];\n";
        if (file_put_contents($auth_file, $contents) === false) {
            $password_change_msg = 'Could not update password file. Check folder permissions.';
            $password_change_error = true;
        } else {
            @chmod($auth_file, 0600);
            $stored_hash = $hash;
            $password_change_msg = 'Password updated successfully.';
        }
    }
}


if (!file_exists($content_file)) {
    die("Error: Content file not found at $content_file");
}

$content = json_decode(file_get_contents($content_file), true);

// ──────────────────────────────────────────────────────────────
// Configuration
// ──────────────────────────────────────────────────────────────

// Icon registry mirrored from src/components/Services.astro iconMap.
$service_icons = [
    'Hammer'              => 'Hammer (Renovation)',
    'TrendingUp'          => 'Trending Up (Growth / ROI)',
    'Network'             => 'Network (Coordination)',
    'ClipboardList'       => 'Clipboard (Management)',
    'Building'            => 'Building',
    'House'               => 'House',
    'Wrench'              => 'Wrench (Maintenance)',
    'HardHat'             => 'Hard Hat (Construction)',
    'DollarSign'          => 'Dollar Sign (Finance)',
    'Briefcase'           => 'Briefcase (Business)',
    'Target'              => 'Target (Goals)',
    'Users'               => 'Users (Team)',
    'Shield'              => 'Shield (Trust)',
    'Lightbulb'           => 'Lightbulb (Strategy)',
    'Settings'            => 'Settings (Operations)',
    'Key'                 => 'Key (Ownership)',
    'Calendar'            => 'Calendar (Scheduling)',
    'FileText'            => 'Document',
    'Wallet'              => 'Wallet',
    'Gauge'               => 'Gauge (Performance)',
    'Sparkles'            => 'Sparkles (Premium)',
    'Award'               => 'Award (Quality)',
    'ChartLine'           => 'Line Chart',
    'ChartNoAxesCombined' => 'Bar Chart',
];

$image_slots = [
    'logo'       => __DIR__ . '/../logo.png',
    'hero_bg'    => __DIR__ . '/../images/hero.jpg',
    'why_image'  => __DIR__ . '/../images/why-axis.jpg',
    'area_image' => __DIR__ . '/../images/service-area.jpg',
];

$image_urls = [
    'logo'       => '/logo.png',
    'hero_bg'    => '/images/hero.jpg',
    'why_image'  => '/images/why-axis.jpg',
    'area_image' => '/images/service-area.jpg',
];

// ──────────────────────────────────────────────────────────────
// Save helpers
// ──────────────────────────────────────────────────────────────

function clean_string_array($raw) {
    if (!is_array($raw)) return [];
    $clean = [];
    foreach (array_values($raw) as $val) {
        if (!is_string($val)) continue;
        $val = trim($val);
        if ($val === '') continue;
        $clean[] = $val;
    }
    return $clean;
}

function clean_step_array($raw) {
    if (!is_array($raw)) return [];
    $clean = [];
    foreach (array_values($raw) as $item) {
        if (!is_array($item)) continue;
        $title = trim($item['title'] ?? '');
        $description = trim($item['description'] ?? '');
        if ($title === '' && $description === '') continue;
        $clean[] = ['title' => $title, 'description' => $description];
    }
    return $clean;
}

function update_array_from_post(&$target, $post_data) {
    foreach ($post_data as $key => $value) {
        if (is_array($value) && isset($target[$key])) {
            update_array_from_post($target[$key], $value);
        } else if (isset($target[$key])) {
            $target[$key] = $value;
        }
    }
}

// ──────────────────────────────────────────────────────────────
// Handle Save
// ──────────────────────────────────────────────────────────────

$message = "";
$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save'])) {
    // ── Image uploads ──
    foreach ($image_slots as $field => $dest) {
        if (!isset($_FILES[$field]) || $_FILES[$field]['error'] === UPLOAD_ERR_NO_FILE) continue;
        $f = $_FILES[$field];
        if ($f['error'] !== UPLOAD_ERR_OK) {
            $errors[] = "Upload failed for $field (PHP error code {$f['error']}).";
            continue;
        }
        if (@getimagesize($f['tmp_name']) === false) {
            $errors[] = "$field: uploaded file is not a valid image.";
            continue;
        }
        $dest_dir = dirname($dest);
        if (!is_dir($dest_dir)) @mkdir($dest_dir, 0775, true);
        if (!move_uploaded_file($f['tmp_name'], $dest)) {
            $errors[] = "$field: could not write to $dest. Check folder permissions.";
        }
    }

    // ── Text/JSON updates ──
    if (isset($_POST['data'])) {
        // Variable-length arrays: validate and replace wholesale
        // (update_array_from_post only walks existing keys, so adds wouldn't take.)

        // services.items
        if (isset($_POST['data']['services']['items'])) {
            $clean = [];
            foreach (array_values($_POST['data']['services']['items']) as $item) {
                if (!is_array($item)) continue;
                $title = trim($item['title'] ?? '');
                $description = trim($item['description'] ?? '');
                $icon = $item['icon'] ?? 'Hammer';
                if ($title === '' && $description === '') continue;
                if (!array_key_exists($icon, $service_icons)) $icon = 'Hammer';
                $clean[] = ['title' => $title, 'description' => $description, 'icon' => $icon];
            }
            $content['services']['items'] = $clean;
            unset($_POST['data']['services']['items']);
        }

        // trust_strip
        if (isset($_POST['data']['trust_strip'])) {
            $content['trust_strip'] = clean_string_array($_POST['data']['trust_strip']);
            unset($_POST['data']['trust_strip']);
        }

        // why.items
        if (isset($_POST['data']['why']['items'])) {
            $content['why']['items'] = clean_string_array($_POST['data']['why']['items']);
            unset($_POST['data']['why']['items']);
        }

        // results.items
        if (isset($_POST['data']['results']['items'])) {
            $content['results']['items'] = clean_string_array($_POST['data']['results']['items']);
            unset($_POST['data']['results']['items']);
        }

        // process.steps
        if (isset($_POST['data']['process']['steps'])) {
            $content['process']['steps'] = clean_step_array($_POST['data']['process']['steps']);
            unset($_POST['data']['process']['steps']);
        }

        update_array_from_post($content, $_POST['data']);

        if (!file_put_contents($content_file, json_encode($content, JSON_PRETTY_PRINT))) {
            $errors[] = "Failed to write site-content.json. Check file permissions.";
        }
    }

    $message = empty($errors) ? "Changes saved successfully!" : implode(' ', $errors);
}

// ──────────────────────────────────────────────────────────────
// Render helpers
// ──────────────────────────────────────────────────────────────

function h($v) { echo htmlspecialchars($v ?? '', ENT_QUOTES, 'UTF-8'); }

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Axis Admin - Edit Content</title>
    <style>
        :root {
            --primary: #c8a25d;
            --bg: #0f1115;
            --card: #1a1d23;
            --text: #e0e0e0;
            --border: #2d333b;
        }
        body {
            font-family: 'Inter', system-ui, sans-serif;
            background: var(--bg);
            color: var(--text);
            margin: 0;
            padding: 40px;
        }
        .container { max-width: 900px; margin: 0 auto; }
        header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 40px;
            border-bottom: 1px solid var(--border);
            padding-bottom: 20px;
            position: sticky;
            top: 0;
            background: var(--bg);
            z-index: 10;
        }
        h1 { color: var(--primary); margin: 0; font-size: 1.5rem; }
        .btn {
            background: var(--primary);
            color: black;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            font-weight: 600;
        }
        .btn:hover { filter: brightness(1.1); }
        .logout-link {
            color: #999;
            font-size: 0.82rem;
            text-decoration: none;
            border: 1px solid var(--border);
            padding: 8px 14px;
            border-radius: 4px;
            transition: color 0.15s, border-color 0.15s;
        }
        .logout-link:hover { color: #f87171; border-color: #3a1e1e; }
        .section-card {
            background: var(--card);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 24px;
            margin-bottom: 24px;
        }
        .section-card h2 {
            margin-top: 0;
            font-size: 1.1rem;
            border-bottom: 1px solid var(--border);
            padding-bottom: 10px;
            color: var(--primary);
        }
        .section-card .helper-note {
            font-size: 0.8rem;
            color: #777;
            margin: -6px 0 16px;
        }
        .form-group { margin-bottom: 16px; }
        label {
            display: block;
            margin-bottom: 6px;
            font-size: 0.85rem;
            color: #888;
        }
        input[type="text"], input[type="password"], textarea, select {
            width: 100%;
            background: #000;
            border: 1px solid var(--border);
            color: white;
            padding: 10px;
            border-radius: 4px;
            box-sizing: border-box;
            font-size: 0.9rem;
        }
        textarea { height: 80px; resize: vertical; }
        .alert {
            background: #1e3a2f;
            color: #4ade80;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        .alert.error { background: #3a1e1e; color: #f87171; }
        .row { display: flex; gap: 15px; }
        .col { flex: 1; }

        /* Image slot */
        .image-slot {
            display: grid;
            grid-template-columns: 140px 1fr;
            gap: 16px;
            align-items: center;
            padding: 12px;
            background: #0d0f13;
            border: 1px solid var(--border);
            border-radius: 6px;
            margin-bottom: 14px;
        }
        .image-slot .preview {
            width: 140px;
            height: 90px;
            background: #000 center/cover no-repeat;
            border: 1px solid var(--border);
            border-radius: 4px;
        }
        .image-slot .preview.contain { background-size: contain; }
        .image-slot label { margin: 0 0 6px 0; color: #aaa; font-weight: 600; }
        .image-slot input[type="file"] {
            width: 100%;
            color: #ccc;
            font-size: 0.85rem;
        }
        .image-slot .hint { font-size: 0.75rem; color: #666; margin-top: 4px; }

        /* Repeatable list rows */
        .list-item {
            border: 1px solid var(--border);
            border-radius: 6px;
            padding: 16px;
            margin-bottom: 14px;
            background: #0d0f13;
            position: relative;
        }
        .list-item.list-item-compact { padding: 10px 12px; }
        .list-item .item-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 12px;
        }
        .list-item .item-title-label {
            font-size: 0.78rem;
            font-weight: 600;
            color: var(--primary);
            letter-spacing: 0.05em;
            text-transform: uppercase;
        }
        .list-item-compact .item-header {
            margin-bottom: 0;
            gap: 10px;
        }
        .list-item-compact .item-header input[type="text"] { flex: 1; }
        .btn-secondary {
            background: transparent;
            color: #f87171;
            border: 1px solid #3a1e1e;
            padding: 6px 12px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 0.78rem;
            font-weight: 600;
            flex-shrink: 0;
        }
        .btn-secondary:hover { background: #3a1e1e; }
        .btn-add {
            background: transparent;
            color: var(--primary);
            border: 1px dashed var(--primary);
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            font-weight: 600;
            width: 100%;
            margin-top: 4px;
        }
        .btn-add:hover { background: rgba(200,162,93,0.08); }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>AXIS CONTENT ADMIN</h1>
            <div style="display:flex; gap:12px; align-items:center;">
                <a href="?logout=1" class="logout-link">Logout</a>
                <button form="main-form" name="save" class="btn">Save All Changes</button>
            </div>
        </header>

        <?php if ($message): ?>
            <div class="alert<?php echo empty($errors) ? '' : ' error'; ?>"><?php h($message); ?></div>
        <?php endif; ?>

        <form id="main-form" method="POST" enctype="multipart/form-data">

            <!-- ─── SITE IMAGES ─── -->
            <div class="section-card">
                <h2>Site Images</h2>
                <p class="helper-note">Upload a replacement image. Leave blank to keep the current one. Hard-refresh the site (Ctrl+Shift+R) after saving to bypass browser cache.</p>

                <?php
                $cache_bust = '?v=' . time();
                $image_fields = [
                    'logo'       => ['label' => 'Logo (PNG, transparent background)', 'contain' => true],
                    'hero_bg'    => ['label' => 'Hero / Header Background',             'contain' => false],
                    'why_image'  => ['label' => 'Why Axis Section Image',               'contain' => false],
                    'area_image' => ['label' => 'Service Area Section Image',           'contain' => false],
                ];
                foreach ($image_fields as $field => $meta):
                    $url = $image_urls[$field] . $cache_bust;
                    $exists = file_exists($image_slots[$field]);
                ?>
                    <div class="image-slot">
                        <div class="preview <?php echo $meta['contain'] ? 'contain' : ''; ?>" style="background-image: url('<?php h($url); ?>');"></div>
                        <div>
                            <label><?php h($meta['label']); ?></label>
                            <input type="file" name="<?php echo $field; ?>" accept="image/*">
                            <div class="hint"><?php echo $exists ? 'Current: ' . htmlspecialchars($image_urls[$field]) : 'Not uploaded yet'; ?></div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <!-- ─── HERO ─── -->
            <div class="section-card">
                <h2>Hero Section</h2>
                <div class="form-group">
                    <label>Eyebrow</label>
                    <input type="text" name="data[hero][eyebrow]" value="<?php h($content['hero']['eyebrow'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Main Title</label>
                    <input type="text" name="data[hero][title]" value="<?php h($content['hero']['title'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Lead Text</label>
                    <textarea name="data[hero][lead]"><?php h($content['hero']['lead'] ?? ''); ?></textarea>
                </div>
                <div class="row">
                    <div class="col">
                        <label>Primary CTA Text</label>
                        <input type="text" name="data[hero][cta_primary_text]" value="<?php h($content['hero']['cta_primary_text'] ?? ''); ?>">
                    </div>
                    <div class="col">
                        <label>Primary CTA Link</label>
                        <input type="text" name="data[hero][cta_primary_link]" value="<?php h($content['hero']['cta_primary_link'] ?? ''); ?>">
                    </div>
                </div>
                <div class="row" style="margin-top:15px;">
                    <div class="col">
                        <label>Secondary CTA Text</label>
                        <input type="text" name="data[hero][cta_secondary_text]" value="<?php h($content['hero']['cta_secondary_text'] ?? ''); ?>">
                    </div>
                    <div class="col">
                        <label>Secondary CTA Link</label>
                        <input type="text" name="data[hero][cta_secondary_link]" value="<?php h($content['hero']['cta_secondary_link'] ?? ''); ?>">
                    </div>
                </div>
                <div class="form-group" style="margin-top:15px;">
                    <label>Note (small text under buttons)</label>
                    <input type="text" name="data[hero][note]" value="<?php h($content['hero']['note'] ?? ''); ?>">
                </div>
            </div>

            <!-- ─── TRUST STRIP ─── -->
            <div class="section-card">
                <h2>Trust Strip (Tagline Bar)</h2>
                <p class="helper-note">Short tags shown in the strip under the hero. Order is preserved.</p>

                <div id="trust-list" data-name-prefix="data[trust_strip]">
                    <?php foreach (($content['trust_strip'] ?? []) as $i => $val): ?>
                        <div class="list-item list-item-compact">
                            <div class="item-header">
                                <input type="text" name="data[trust_strip][<?php echo $i; ?>]" value="<?php h($val); ?>">
                                <button type="button" class="btn-secondary" onclick="removeListItem(this, 'trust-list')">Remove</button>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <button type="button" class="btn-add" onclick="addListItem('trust-list', 'trust-item-template')">+ Add Tag</button>

                <template id="trust-item-template">
                    <div class="list-item list-item-compact">
                        <div class="item-header">
                            <input type="text" name="data[trust_strip][__INDEX__]" value="">
                            <button type="button" class="btn-secondary" onclick="removeListItem(this, 'trust-list')">Remove</button>
                        </div>
                    </div>
                </template>
            </div>

            <!-- ─── ABOUT ─── -->
            <div class="section-card">
                <h2>About Section</h2>
                <div class="form-group">
                    <label>Eyebrow</label>
                    <input type="text" name="data[about][eyebrow]" value="<?php h($content['about']['eyebrow'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Title</label>
                    <input type="text" name="data[about][title]" value="<?php h($content['about']['title'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Content</label>
                    <textarea name="data[about][content]"><?php h($content['about']['content'] ?? ''); ?></textarea>
                </div>
            </div>

            <!-- ─── SERVICES ─── -->
            <div class="section-card">
                <h2>Services Cards</h2>
                <p class="helper-note">Add, remove, or rearrange the cards shown in the Services carousel. Use <code style="background:#000;padding:1px 4px;border-radius:3px;">\n</code> in the title to force a line break.</p>

                <div class="form-group">
                    <label>Eyebrow</label>
                    <input type="text" name="data[services][eyebrow]" value="<?php h($content['services']['eyebrow'] ?? ''); ?>">
                </div>

                <div id="services-list" data-name-prefix="data[services][items]">
                    <?php foreach (($content['services']['items'] ?? []) as $i => $item): ?>
                        <div class="list-item">
                            <div class="item-header">
                                <span class="item-title-label">Card #<span class="item-num"><?php echo $i + 1; ?></span></span>
                                <button type="button" class="btn-secondary" onclick="removeListItem(this, 'services-list')">Remove</button>
                            </div>
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" name="data[services][items][<?php echo $i; ?>][title]" value="<?php h($item['title'] ?? ''); ?>">
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea name="data[services][items][<?php echo $i; ?>][description]"><?php h($item['description'] ?? ''); ?></textarea>
                            </div>
                            <div class="form-group">
                                <label>Icon</label>
                                <select name="data[services][items][<?php echo $i; ?>][icon]">
                                    <?php foreach ($service_icons as $key => $label): ?>
                                        <option value="<?php h($key); ?>"<?php echo (($item['icon'] ?? '') === $key) ? ' selected' : ''; ?>><?php h($label); ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <button type="button" class="btn-add" onclick="addListItem('services-list', 'service-item-template')">+ Add Card</button>

                <template id="service-item-template">
                    <div class="list-item">
                        <div class="item-header">
                            <span class="item-title-label">Card #<span class="item-num">__NUM__</span></span>
                            <button type="button" class="btn-secondary" onclick="removeListItem(this, 'services-list')">Remove</button>
                        </div>
                        <div class="form-group">
                            <label>Title</label>
                            <input type="text" name="data[services][items][__INDEX__][title]" value="">
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="data[services][items][__INDEX__][description]"></textarea>
                        </div>
                        <div class="form-group">
                            <label>Icon</label>
                            <select name="data[services][items][__INDEX__][icon]">
                                <?php foreach ($service_icons as $key => $label): ?>
                                    <option value="<?php h($key); ?>"><?php h($label); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </template>
            </div>

            <!-- ─── WHY AXIS ─── -->
            <div class="section-card">
                <h2>Why Axis Section</h2>
                <p class="helper-note">Image is editable in the Site Images section above.</p>

                <div class="form-group">
                    <label>Eyebrow</label>
                    <input type="text" name="data[why][eyebrow]" value="<?php h($content['why']['eyebrow'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Title (use \n for a line break)</label>
                    <input type="text" name="data[why][title]" value="<?php h($content['why']['title'] ?? ''); ?>">
                </div>

                <label>Reasons (bulleted list)</label>
                <div id="why-list" data-name-prefix="data[why][items]" style="margin-top:6px;">
                    <?php foreach (($content['why']['items'] ?? []) as $i => $val): ?>
                        <div class="list-item list-item-compact">
                            <div class="item-header">
                                <input type="text" name="data[why][items][<?php echo $i; ?>]" value="<?php h($val); ?>">
                                <button type="button" class="btn-secondary" onclick="removeListItem(this, 'why-list')">Remove</button>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <button type="button" class="btn-add" onclick="addListItem('why-list', 'why-item-template')">+ Add Reason</button>

                <template id="why-item-template">
                    <div class="list-item list-item-compact">
                        <div class="item-header">
                            <input type="text" name="data[why][items][__INDEX__]" value="">
                            <button type="button" class="btn-secondary" onclick="removeListItem(this, 'why-list')">Remove</button>
                        </div>
                    </div>
                </template>
            </div>

            <!-- ─── RESULTS ─── -->
            <div class="section-card">
                <h2>Results Section</h2>
                <div class="form-group">
                    <label>Eyebrow</label>
                    <input type="text" name="data[results][eyebrow]" value="<?php h($content['results']['eyebrow'] ?? ''); ?>">
                </div>

                <label>Results (use \n for a line break in any item)</label>
                <div id="results-list" data-name-prefix="data[results][items]" style="margin-top:6px;">
                    <?php foreach (($content['results']['items'] ?? []) as $i => $val): ?>
                        <div class="list-item list-item-compact">
                            <div class="item-header">
                                <input type="text" name="data[results][items][<?php echo $i; ?>]" value="<?php h($val); ?>">
                                <button type="button" class="btn-secondary" onclick="removeListItem(this, 'results-list')">Remove</button>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <button type="button" class="btn-add" onclick="addListItem('results-list', 'results-item-template')">+ Add Result</button>

                <template id="results-item-template">
                    <div class="list-item list-item-compact">
                        <div class="item-header">
                            <input type="text" name="data[results][items][__INDEX__]" value="">
                            <button type="button" class="btn-secondary" onclick="removeListItem(this, 'results-list')">Remove</button>
                        </div>
                    </div>
                </template>
            </div>

            <!-- ─── PROCESS ─── -->
            <div class="section-card">
                <h2>Our Process</h2>
                <p class="helper-note">Steps shown in the numbered timeline. Use \n in the title for a line break.</p>

                <div class="form-group">
                    <label>Eyebrow</label>
                    <input type="text" name="data[process][eyebrow]" value="<?php h($content['process']['eyebrow'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Title</label>
                    <input type="text" name="data[process][title]" value="<?php h($content['process']['title'] ?? ''); ?>">
                </div>

                <div id="process-list" data-name-prefix="data[process][steps]">
                    <?php foreach (($content['process']['steps'] ?? []) as $i => $step): ?>
                        <div class="list-item">
                            <div class="item-header">
                                <span class="item-title-label">Step <span class="item-num"><?php echo $i + 1; ?></span></span>
                                <button type="button" class="btn-secondary" onclick="removeListItem(this, 'process-list')">Remove</button>
                            </div>
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" name="data[process][steps][<?php echo $i; ?>][title]" value="<?php h($step['title'] ?? ''); ?>">
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea name="data[process][steps][<?php echo $i; ?>][description]"><?php h($step['description'] ?? ''); ?></textarea>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <button type="button" class="btn-add" onclick="addListItem('process-list', 'process-item-template')">+ Add Step</button>

                <template id="process-item-template">
                    <div class="list-item">
                        <div class="item-header">
                            <span class="item-title-label">Step <span class="item-num">__NUM__</span></span>
                            <button type="button" class="btn-secondary" onclick="removeListItem(this, 'process-list')">Remove</button>
                        </div>
                        <div class="form-group">
                            <label>Title</label>
                            <input type="text" name="data[process][steps][__INDEX__][title]" value="">
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="data[process][steps][__INDEX__][description]"></textarea>
                        </div>
                    </div>
                </template>
            </div>

            <!-- ─── SERVICE AREA ─── -->
            <div class="section-card">
                <h2>Service Area</h2>
                <p class="helper-note">Image is editable in the Site Images section above.</p>

                <div class="form-group">
                    <label>Eyebrow</label>
                    <input type="text" name="data[service_area][eyebrow]" value="<?php h($content['service_area']['eyebrow'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Title (use \n for a line break)</label>
                    <input type="text" name="data[service_area][title]" value="<?php h($content['service_area']['title'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Content</label>
                    <textarea name="data[service_area][content]" style="height:120px;"><?php h($content['service_area']['content'] ?? ''); ?></textarea>
                </div>
            </div>

            <!-- ─── CTA ─── -->
            <div class="section-card">
                <h2>Call to Action</h2>
                <div class="form-group">
                    <label>CTA Title</label>
                    <input type="text" name="data[cta][title]" value="<?php h($content['cta']['title'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>CTA Lead</label>
                    <textarea name="data[cta][lead]"><?php h($content['cta']['lead'] ?? ''); ?></textarea>
                </div>
                <div class="row">
                    <div class="col">
                        <label>Primary Button Text</label>
                        <input type="text" name="data[cta][primary_button_text]" value="<?php h($content['cta']['primary_button_text'] ?? ''); ?>">
                    </div>
                    <div class="col">
                        <label>Primary Button Link</label>
                        <input type="text" name="data[cta][primary_button_link]" value="<?php h($content['cta']['primary_button_link'] ?? ''); ?>">
                    </div>
                </div>
                <div class="row" style="margin-top:15px;">
                    <div class="col">
                        <label>Secondary Button Text</label>
                        <input type="text" name="data[cta][secondary_button_text]" value="<?php h($content['cta']['secondary_button_text'] ?? ''); ?>">
                    </div>
                    <div class="col">
                        <label>Secondary Button Link</label>
                        <input type="text" name="data[cta][secondary_button_link]" value="<?php h($content['cta']['secondary_button_link'] ?? ''); ?>">
                    </div>
                </div>
            </div>

            <!-- ─── FOOTER ─── -->
            <div class="section-card">
                <h2>Footer</h2>
                <div class="form-group">
                    <label>Tagline (use \n for line break)</label>
                    <input type="text" name="data[footer][tagline]" value="<?php h($content['footer']['tagline'] ?? ''); ?>">
                </div>
                <div class="row">
                    <div class="col">
                        <label>Phone (display)</label>
                        <input type="text" name="data[footer][phone]" value="<?php h($content['footer']['phone'] ?? ''); ?>">
                    </div>
                    <div class="col">
                        <label>Phone Link (tel:...)</label>
                        <input type="text" name="data[footer][phone_link]" value="<?php h($content['footer']['phone_link'] ?? ''); ?>">
                    </div>
                </div>
                <div class="row" style="margin-top:15px;">
                    <div class="col">
                        <label>Email (display)</label>
                        <input type="text" name="data[footer][email]" value="<?php h($content['footer']['email'] ?? ''); ?>">
                    </div>
                    <div class="col">
                        <label>Email Link (mailto:...)</label>
                        <input type="text" name="data[footer][email_link]" value="<?php h($content['footer']['email_link'] ?? ''); ?>">
                    </div>
                </div>
                <div class="form-group" style="margin-top:15px;">
                    <label>Service Area Label</label>
                    <input type="text" name="data[footer][service_area]" value="<?php h($content['footer']['service_area'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Copyright Text</label>
                    <input type="text" name="data[footer][copyright]" value="<?php h($content['footer']['copyright'] ?? ''); ?>">
                </div>
                <div class="form-group">
                    <label>Disclaimer</label>
                    <textarea name="data[footer][disclaimer]" style="height:120px;"><?php h($content['footer']['disclaimer'] ?? ''); ?></textarea>
                </div>
            </div>

            <p style="text-align: center; color: #555; font-size: 0.8rem;">
                Note: Saving updates public/site-content.json and any uploaded images in public/. Hard-refresh the site to bypass browser cache.
            </p>
        </form>

        <!-- ─── CHANGE PASSWORD (separate form so it doesn't submit with content) ─── -->
        <form method="POST" class="section-card" style="margin-top: 40px;">
            <h2 style="margin-top:0; font-size:1.1rem; border-bottom:1px solid var(--border); padding-bottom:10px; color:var(--primary);">Change Admin Password</h2>
            <?php if ($password_change_msg): ?>
                <div class="alert<?php echo $password_change_error ? ' error' : ''; ?>"><?php h($password_change_msg); ?></div>
            <?php endif; ?>
            <div class="form-group">
                <label>Current Password</label>
                <input type="password" name="current_password" autocomplete="current-password" required>
            </div>
            <div class="row">
                <div class="col">
                    <label>New Password (min 6 chars)</label>
                    <input type="password" name="new_password" autocomplete="new-password" required>
                </div>
                <div class="col">
                    <label>Confirm New Password</label>
                    <input type="password" name="confirm_password" autocomplete="new-password" required>
                </div>
            </div>
            <button type="submit" name="change_password" value="1" class="btn" style="margin-top:18px;">Update Password</button>
        </form>
    </div>

    <script>
        // Escape special regex characters in a string so it can be used inside a RegExp literal.
        function escapeRegex(s) {
            return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        }

        function reindexList(listId) {
            const list = document.getElementById(listId);
            if (!list) return;
            const prefix = list.dataset.namePrefix; // e.g. "data[trust_strip]"
            const escaped = escapeRegex(prefix);
            const pattern = new RegExp(escaped + '\\[\\d+\\]');
            list.querySelectorAll('.list-item').forEach((item, i) => {
                item.dataset.index = i;
                const numEl = item.querySelector('.item-num');
                if (numEl) numEl.textContent = i + 1;
                item.querySelectorAll('[name]').forEach(el => {
                    el.name = el.name.replace(pattern, prefix + '[' + i + ']');
                });
            });
        }

        function addListItem(listId, templateId) {
            const list = document.getElementById(listId);
            const tpl  = document.getElementById(templateId);
            if (!list || !tpl) return;
            const newIndex = list.querySelectorAll('.list-item').length;
            const clone = tpl.content.cloneNode(true);
            clone.querySelectorAll('[name]').forEach(el => {
                el.name = el.name.replace(/__INDEX__/g, newIndex);
            });
            const wrapper = clone.querySelector('.list-item');
            wrapper.dataset.index = newIndex;
            const numEl = wrapper.querySelector('.item-num');
            if (numEl) numEl.textContent = newIndex + 1;
            list.appendChild(clone);
        }

        function removeListItem(btn, listId) {
            const item = btn.closest('.list-item');
            if (!item) return;
            const list = document.getElementById(listId);
            const remaining = list.querySelectorAll('.list-item').length;
            if (remaining <= 1) {
                alert('At least one item is required.');
                return;
            }
            if (!confirm('Remove this item?')) return;
            item.remove();
            reindexList(listId);
        }
    </script>
</body>
</html>
